apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - name: web
      namespace: default
      sectionName: http
  hostnames:
    - localhost
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
